# Generated by Django 4.2.6 on 2023-10-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0002_alter_subject_image_alter_subject_name_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Theme Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='studyPlatformApi.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FilePathField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Links', to='studyPlatformApi.content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Content Image')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studyPlatformApi.content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Content file')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studyPlatformApi.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='theme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='studyPlatformApi.theme'),
        ),
    ]
