# Generated by Django 4.2.6 on 2023-10-10 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0003_content_alter_category_name_theme_contentvideolink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(upload_to='content_images/'),
        ),
        migrations.AlterField(
            model_name='contentvideolink',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to='subject_images/', verbose_name='Subject Image'),
        ),
    ]
