# Generated by Django 4.2.6 on 2023-10-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0004_example_alter_category_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.AddField(
            model_name='category',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
