# Generated by Django 4.2.6 on 2023-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0005_delete_example_category_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(verbose_name='Content text'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(upload_to='content_files/', verbose_name='Content file'),
        ),
    ]
