# Generated by Django 4.2.6 on 2023-10-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0006_contentfile_description_alter_content_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideolink',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='studyPlatformApi.content'),
        ),
    ]
