# Generated by Django 4.2.6 on 2023-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0008_alter_category_id_alter_content_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
