# Generated by Django 4.2.6 on 2023-10-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0011_remove_category_has_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='studyPlatformApi.category'),
        ),
    ]
