# Generated by Django 4.2.6 on 2023-10-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0012_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
