# Generated by Django 4.2.6 on 2023-10-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0015_alter_theme_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='theme',
            field=models.OneToOneField(limit_choices_to={'content__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='studyPlatformApi.theme'),
        ),
    ]
