# Generated by Django 4.2.6 on 2023-10-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0018_rename_contentfile_themefile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themefile',
            old_name='content',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='themeimage',
            old_name='content',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='themevideolink',
            old_name='content',
            new_name='theme',
        ),
    ]
