# Generated by Django 4.2.6 on 2023-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0019_rename_content_themefile_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themevideolink',
            name='theme',
            field=models.ManyToManyField(related_name='video_links', to='studyPlatformApi.theme'),
        ),
    ]
