# Generated by Django 4.2.6 on 2023-10-12 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0020_alter_themevideolink_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themevideolink',
            name='link',
        ),
        migrations.AddField(
            model_name='themevideolink',
            name='video_links',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='video link'),
            preserve_default=False,
        ),
    ]
