# Generated by Django 4.2.6 on 2023-10-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0023_rename_links_themevideolink_video_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themevideolink',
            old_name='video_links',
            new_name='link',
        ),
    ]
