# Generated by Django 4.2.6 on 2023-10-13 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0024_rename_video_links_themevideolink_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themefile',
            name='description',
        ),
        migrations.AddField(
            model_name='themefile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
