# Generated by Django 4.2.6 on 2023-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0025_remove_themefile_description_themefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='themevideolink',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
