# Generated by Django 4.2.6 on 2023-10-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0026_themevideolink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='studyPlatformApi.category'),
        ),
    ]
