# Generated by Django 4.2.6 on 2023-10-15 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0027_alter_theme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeimage',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
