# Generated by Django 4.2.6 on 2023-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlatformApi', '0030_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='studyPlatformApi.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subject name'),
        ),
    ]
